language: node_js
node_js:
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- '6.0'
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: eIVmyU17TBnm7xWUGYcSLxU2Mz3XyryVz1YcRFBSWBJPvrc3bFuuXsJpk4zuPUrRrygumYtxTfcSbnAhnmcMO/NUbeWZyl62tR6CAxSVXI3tGdrp06LP8LOnBN4Sz99aPyuwbReuse6gEXAjD06kNVCgozFfmFW4y4fXFeowkSM=
  on:
    tags: true
    node: '6.0'
